// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Funq.Build
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using Funq.Build;
    using System;
    
    
    #line 1 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class FunqletTemplate : FunqletTemplateBase
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public virtual string TransformText()
        {
            this.GenerationEnvironment = null;
            this.Write("using System;\r\nusing Funq;\r\n\r\nnamespace ");
            
            #line 10 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TargetNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic partial class Funqlet : IFunqlet\r\n\t{\r\n\t\tpublic void Configure(Contai" +
                    "ner container)\r\n\t\t{\r\n");
            
            #line 16 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"

this.codegen.BeginInit();
this.codegen.EndInit();

foreach (var item in this.Exports)
{

            
            #line default
            #line hidden
            this.Write("\t\t\tcontainer.Register<");
            
            #line 23 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Contract.Type));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 23 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Contract.Name != null ? Quote(item.Contract.Name) + ", " : ""));
            
            #line default
            #line hidden
            this.Write("c => \r\n\t\t\t\tnew ");
            
            #line 24 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Implementation));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 24 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Render(item.Parameters)));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 24 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"

if (item.Properties.Any())
{

            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t{ \r\n\t\t\t\t\t");
            
            #line 29 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Render(item.Properties)));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t}");
            
            #line 30 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"

}
				
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 33 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tDoConfigure(container);\r\n\t\t}\r\n\r\n\t\t/// <summary>\r\n\t\t/// Extensibility hook fo" +
                    "r custom registration code in the owning project.\t\t\r\n\t\t/// </summary>\r\n\t\tpartial" +
                    " void DoConfigure(Container container);\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 46 "D:\Code\clarius\funq\src\Core\Funq.Build\FunqletTemplate.tt"

/// <summary>
/// Target namespace passed-in by the task for the generated funqlet class.
/// </summary>
internal string TargetNamespace { get; set; }

/// <summary>
/// Exports from the assemblies with copylocal=true.
/// </summary>
internal IEnumerable<Export> Exports { get; set; }

private CodeGeneration codegen = new CodeGeneration();

private string Render(IEnumerable<Import> parameters)
{
    return string.Join(", ", parameters
        .Select(import => Resolve(import))
        .ToArray());
}

private string Render(IEnumerable<PropertyImport> properties)
{
    return string.Join(", \r\n", properties
        .Select(prop => prop.Name + " = " + Resolve(prop))
        .ToArray());
}

private string Resolve(Import import)
{
    var invocation = "c.";
    if (import.AllowDefault)
        invocation += "Try";

    if (import.Contract.Name != null)
        invocation += "ResolveNamed";
    else
        invocation += "Resolve";

    invocation += "<" + codegen.GetTypeName(import.Contract.Type) + ">";
    invocation += "(" + Quote(import.Contract.Name) + ")";

    return invocation;
}

private string Quote(string value)
{
    return string.IsNullOrEmpty(value) ?
        "" :
        "\"" + value + "\"";
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class FunqletTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
    }
    #endregion
}
